# This file is part of django-inline-translations.
# https://github.com/akolpakov/django-inline-translations

# Licensed under the MIT license:
# http://www.opensource.org/licenses/MIT-license
# Copyright (c) 2015, Andrey Kolpakov <aakolpakov@gmail.com>

language: python

python:
    - "2.7"
    - "3.5"
    - "pypy"

install:
    # install python requirements
    - make setup

script:
    # run tests
    - make test